import { useState } from 'react';
import { ArrowRight, Inbox, Search } from 'lucide-react';
import { DashboardLayout } from '../components/DashboardLayout';
import { AthleteTransferDetailModal } from '../components/athlete-transfers/AthleteTransferDetailModal';
import { transferStatusLabel, transferStatusStyle } from '../components/athlete-transfers/transferPresentation';
import { useAthleteTransfers } from '../hooks/queries/useAthleteTransfers';

const tabs = [{ id: 'inbox', label: 'Kotak Masuk' }, { id: 'outbox', label: 'Kotak Keluar' }, { id: 'history', label: 'Riwayat' }];
const statuses = ['', 'pending_destination', 'pending_koni', 'completed', 'rejected_destination', 'rejected_koni', 'cancelled'];

export function AthleteTransfersPage() {
  const [box, setBox] = useState('inbox'); const [status, setStatus] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [selectedId, setSelectedId] = useState(null);
  const filters = { box, status: status || undefined, search: search || undefined, page, per_page: 15 };
  const { data, isLoading, isError } = useAthleteTransfers(filters);
  const changeTab = (value) => { setBox(value); setPage(1); };
  return <DashboardLayout><div className="space-y-5 p-4 sm:p-6">
    <div><h1 className="text-2xl font-bold text-slate-900">Transfer Atlet</h1><p className="text-sm text-slate-500">Kelola perpindahan Atlet antar-KONI kabupaten/kota dengan riwayat persetujuan lengkap.</p></div>
    <div className="flex flex-wrap gap-2 rounded-2xl bg-slate-100 p-1.5">{tabs.map((tab) => <button key={tab.id} onClick={() => changeTab(tab.id)} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${box === tab.id ? 'bg-white text-red-700 shadow-sm' : 'text-slate-600'}`}>{tab.label}</button>)}</div>
    <div className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[1fr_260px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Cari Atlet atau organisasi" className="w-full rounded-xl border border-slate-300 py-2.5 pl-10 pr-3" /></label><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="rounded-xl border border-slate-300 px-3 py-2.5">{statuses.map((value) => <option key={value} value={value}>{value ? transferStatusLabel(value) : 'Semua status'}</option>)}</select></div>
    <div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{isLoading ? <div className="p-14 text-center text-slate-500">Memuat transfer...</div> : isError ? <div className="p-14 text-center text-red-600">Data transfer gagal dimuat.</div> : !data?.data?.length ? <div className="p-14 text-center"><Inbox className="mx-auto mb-3 h-9 w-9 text-slate-300" /><p className="font-semibold text-slate-600">Belum ada pengajuan pada kotak ini.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px]"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Atlet</th><th className="px-5 py-3">Perpindahan</th><th className="px-5 py-3">Tanggal Efektif</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y">{data.data.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-slate-800">{item.athlete_name_snapshot}</p><p className="text-xs text-slate-500">{item.cabor_name_snapshot || '-'}</p></td><td className="px-5 py-4 text-sm"><div className="flex items-center gap-2"><span>{item.source_organization_name_snapshot}</span><ArrowRight className="h-4 w-4 text-slate-400" /><span className="font-semibold">{item.destination_organization_name_snapshot}</span></div></td><td className="px-5 py-4 text-sm">{new Date(`${item.effective_date}T00:00:00`).toLocaleDateString('id-ID')}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${transferStatusStyle(item.status)}`}>{transferStatusLabel(item.status)}</span></td><td className="px-5 py-4 text-right"><button onClick={() => setSelectedId(item.id)} className="rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">Detail</button></td></tr>)}</tbody></table></div>}</div>
    {data?.last_page > 1 && <div className="flex items-center justify-end gap-3"><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Sebelumnya</button><span className="text-sm text-slate-500">Halaman {page} dari {data.last_page}</span><button disabled={page >= data.last_page} onClick={() => setPage((v) => v + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Berikutnya</button></div>}
  </div><AthleteTransferDetailModal id={selectedId} isOpen={Boolean(selectedId)} onClose={() => setSelectedId(null)} /></DashboardLayout>;
}
